# Generated by Django 5.0.1 on 2024-02-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Categoria'),
        ),
    ]
